### ISSUE TITLE
I can't install Archiconda

### ISSUE THREAD

**Issue by tunayeniyayla** [Archiconda/build-tools#23]
- I downloaded the "Archiconda3-0.2.3-Linux-aarch64.sh" file.

- `chmod + x Archiconda3-0.2.3-Linux-aarch64.sh`
command i used.

- `./Archiconda3-0.2.3-linux-aarch64.sh`
I did but I get an error like this:

> PREFIX=/home/tunahan/archiconda3
installing: python-3.7.1-h39be038_1002 ...
./Archiconda3-0.2.3-Linux-aarch64.sh: 342: ./Archiconda3-0.2.3-Linux-aarch64.sh: /home/tunahan/archiconda3/bin/python: not found

**Comment by hmaarrfk** [comment]
what platform are you on? Are you on aarch64? or aarch32?

**Comment by tunayeniyayla** [comment]
aarch64

**Comment by hmaarrfk** [comment]
can you output the full output of the result? what is your motherboard? what is your microcontroller?

**Comment by tunayeniyayla** [comment]
CPU: Qualcomm Technologies, Inc MSM8996pro 
GPU: mdssfb_90000 mdssfb_a0000
Kernel: aarch64 Linux 3.18.71-perf-ga01336f
OS: Debian 10 buster

**Comment by hmaarrfk** [comment]
do other versions install?

**Comment by tunayeniyayla** [comment]
- `./archiconda3-0.2.2-linux-aarch64.sh`
I get the same error.

- `./archiconda3-0.2.1-linux-aarch64.sh`
I get the same error.

- `./archiconda3-0.2.0-linux-aarch64.sh`
I get the same error.

- `./archiconda3Builder-0.1.2-linux-aarch64.sh`
I get the same error.

- `./archiconda3-0.1.1-linux-aarch64.sh`
I get the same error.

Yes, I got the same error in all versions.

**Comment by hmaarrfk** [comment]
This is strange. I have been able to install on Ubuntu 18.04. Is there more to the output that you didn't copy over? If so, could you please copy it?

**Comment by tunayeniyayla** [comment]
There are more standard installation stages above. I just copied a little bit of the error now.

> Archiconda3 will now be installed into this location:
> /root/archiconda3
> 
>   - Press ENTER to confirm the location
>   - Press CTRL-C to abort the installation
>   - Or specify a different location below
> 
> [/root/archiconda3] >>> /home/tunahan/archiconda3
> PREFIX=/home/tunahan/archiconda3
> installing: python-3.7.0-hab5db58_3 ...
> ./Archiconda3-0.1.1-Linux-aarch64.sh: 342: ./Archiconda3-0.1.1-Linux-aarch64.sh: /home/tunahan/archiconda3/bin/python: not found
>

**Comment by hmaarrfk** [comment]
did you install system python? you might need some kind of python installed.

**Comment by tunayeniyayla** [comment]
> [I] ╭─tunahan at localhost in /home/tunahan/Downloads
> ╰─λ python -V  
> Python 2.7.16
> [I] ╭─tunahan at localhost in /home/tunahan/Downloads
> ╰─λ python3 -V                                                                          0 < 22:22:11
> Python 3.7.3
The answer came to my mind when writing, I use the fish shell. is it a problem?

**Comment by hmaarrfk** [comment]
maybe, why not just type `bash` and try to install from there.

**Comment by hmaarrfk** [comment]
I've installed this in CIs and on QEMU all the time. Not sure why you having a problem :/ could be fish.

The older installers were used to make most packages.

**Comment by tunayeniyayla** [comment]
Unfortunately, I received the same error in the normal shell.
I'm guessing there's no solution to that. The problem is the big possibility; i have installed operating system on the Xiaomi Mi 5S Plus.

**Comment by tunayeniyayla** [comment]
All I wanted to do was build a virtual environment and develop software with the Spyder IDE, but I think it won't happen.

**Comment by hmaarrfk** [comment]
I think conda is a pure python package on pypi.

Try installing that, then you should be able to create conda environments.

You would have to add the conda forge channel, which has numpy, but many other packages might have to be built from source

**Comment by tunayeniyayla** [comment]
Can you describe what you mean? I do not want to engage you, do you have any relevant sources? My English is a little weak, I don't understand what you mean, how should I do it?

**Comment by hmaarrfk** [comment]
It seems you are using a very new distribution. Maybe using something like Ubuntu 18.04 will be better?

**Comment by tunayeniyayla** [comment]
Yes, as you said, it wasn't possible to install other operating systems like Ubuntu 18.04, but none of them worked as stable as the current operating system.

**Comment by gzbbdg** [comment]
I got the same error using helmuthva/jetson-ml-base image from hub.docker.com (Ubuntu 18.10).

**Comment by hmaarrfk** [comment]
Are you knowledgeable enough to try to remake the installer yourself? I think I have a simple makefile. Please do report.

**Comment by hmaarrfk** [comment]
Well we've made some progress on things. 

https://github.com/conda-forge/miniforge/pull/2

We probably won't release for a bit, but you can build it yourself locally if you want.

**Comment by tunayeniyayla** [comment]
How can I do it locally, is there any resources on this?

**Comment by hmaarrfk** [comment]
We've now released Miniconda for aarch64

https://github.com/conda-forge/miniforge/releases

**Comment by hmaarrfk** [comment]
Sorry, we just called it Miniforge, not miniconda
