### ISSUE TITLE
Is there repos for China? I can not visit the default repo if it's without vnp.

### ISSUE THREAD

**Issue by qq3d1415926** [Archiconda/build-tools#24]
Or can I create one giving service to ?

**Comment by hmaarrfk** [comment]
You are free to create a mirror for china. I don't really know what works and what doesn't for china.

That said, most of this effort has been moved as part of conda-forge itself, and now, many packages, including numpy, scipy, and others are built for aarch64 as part of conda-forge.

**Comment by qq3d1415926** [comment]
> You are free to create a mirror for china. I don't really know what works and what doesn't for china.
> 
> That said, most of this effort has been moved as part of conda-forge itself, and now, many packages, including numpy, scipy, and others are built for aarch64 as part of conda-forge.

thanks
