### ISSUE TITLE
Installing Opencv

### ISSUE THREAD

**Issue by Zumbalamambo** [Archiconda/build-tools#27]
How do I install opencv within my conda environment?

I tried to use `sudo apt-get installl opencv-python ` which works but it installs everything globally I guess. It wont let me import the packages within my conda environment.

**Comment by hmaarrfk** [comment]
You will have to wait until we build it for conda.

Please follow progress on conda forge

**Comment by Zumbalamambo** [comment]
@hmaarrfk that would save lives!

**Comment by hmaarrfk** [comment]
You can always install it from the system installation. But everything will have to use the system installers

**Comment by Zumbalamambo** [comment]
@hmaarrfk may I know what do you mean by system installation? I have tried to build it form the source but it always installs it outside the conda environment :(

**Comment by hmaarrfk** [comment]
```
sudo apt install python3-opencv
```

That will installit for your python that is installed in `/usr/bin/python3`, but not for your conda environment.

We are waiting for qt to get compiled for aarch, but that is a rather huge dependency... https://conda-forge.org/status/
