### ISSUE TITLE
Archiconda3-0.2.3-Linux-aarch64.sh: line 342: /home/pi/archiconda3/bin/python: No such file or directory

### ISSUE THREAD

**Issue by ztingz** [Archiconda/build-tools#28]
How to deal with this situation? My hardware is Raspberry PI 4B, and my OS is Raspbian(AARCH64).

There exists this file:
~/archiconda3/bin $ ls -lah
total 44K
drwxr-xr-x  2 pi pi 4.0K Dec 25 15:45 .
drwxr-xr-x 10 pi pi 4.0K Dec 25 15:27 ..
lrwxrwxrwx  1 pi pi    8 Feb 26  2019 2to3 -> 2to3-3.7
-rwxr-xr-x  1 pi pi  123 Feb 26  2019 2to3-3.7
lrwxrwxrwx  1 pi pi    7 Feb 26  2019 idle3 -> idle3.7
-rwxr-xr-x  1 pi pi  121 Feb 26  2019 idle3.7
lrwxrwxrwx  1 pi pi    8 Feb 26  2019 pydoc -> pydoc3.7
lrwxrwxrwx  1 pi pi    8 Feb 26  2019 pydoc3 -> pydoc3.7
-rwxr-xr-x  1 pi pi  106 Feb 26  2019 pydoc3.7
lrwxrwxrwx  1 pi pi    9 Feb 26  2019 python -> python3.7
lrwxrwxrwx  1 pi pi    9 Feb 26  2019 python3 -> python3.7
-rwxr-xr-x  1 pi pi  14K Dec 25 15:45 python3.7
lrwxrwxrwx  1 pi pi   17 Feb 26  2019 python3.7-config -> python3.7m-config
lrwxrwxrwx  1 pi pi    9 Feb 26  2019 python3.7m -> python3.7
-rwxr-xr-x  1 pi pi 3.3K Feb 26  2019 python3.7m-config
lrwxrwxrwx  1 pi pi   17 Feb 26  2019 python3-config -> python3.7m-config
lrwxrwxrwx  1 pi pi   10 Feb 26  2019 pyvenv -> pyvenv-3.7
-rwxr-xr-x  1 pi pi  463 Feb 26  2019 pyvenv-3.7

and python is installed

**Comment by hmaarrfk** [comment]
this project is mostly defunct. Pleas see https://github.com/conda-forge/miniforge/
