### ISSUE TITLE
bioconda tools

### ISSUE THREAD

**Issue by stefanscripts** [Archiconda/build-tools#32]
Hi,

 I am running Archiconda on my Jetson Xavier NX. I am trying to install tools from bioconda and conda-forge, but I always get an error that the tools aren't available from my current channels - even thoguh I have both bioconda and conda-forge channels in my list.

Did anyone experience the same issue? Any fixes?

Cheers and thanks,
Stefan

**Comment by hmaarrfk** [comment]
this project is mostly defunct and had been integrated into conda forge. unsure about bioconda

**Comment by stefanscripts** [comment]
So what does that mean for my issue? Do you have any ideas what to do?

**Comment by hmaarrfk** [comment]
did installing miniforge work? if so, that was the extent of the ambitions of this project.

**Comment by hmaarrfk** [comment]
if not, please post an issue on the miniforge installer. i am interested in ensuring that miniforge works with the appropriate haedware and kernel

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/miniforge/

**Comment by stefanscripts** [comment]
Hi,

Sorry for my late reply. I got derailed with other stuff. I'm off to Peru in two weeks and working n setting up my Jetson Xavier NX again. Miniorge was easy to install and it works well for creating environments, but installing tools from bioconda keeps failing.

(NGSpeciesID) ***@***.***:~/Downloads$ conda install -c bioconda minimap2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

- minimap2

Current channels:

- https://conda.anaconda.org/bioconda/linux-aarch64
- https://conda.anaconda.org/bioconda/noarch
- https://conda.anaconda.org/conda-forge/linux-aarch64
- https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org

and use the search bar at the top of the page.

Any idea what's going on??

Cheers and thanks!
Stefan

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
